version: '3'
services:
  db:
    image: postgres:10
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
    command: ["python", "manage.py", "runserver"]
      - ./django_crud:/usr/src/app

volumes:
  dbdata:
