version: '3'
services:
  db:
    image: postgres:10
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./django_todo:/usr/src/app
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  dbdata:
